import { useQuery } from '@tanstack/react-query'
import { Sparkles } from 'lucide-react'
import { api } from '../lib/api'
import { qk } from '../lib/queryKeys'
import { Card, PageHeader } from '../components/common/primitives'
import { QueryBoundary } from '../components/common/states'

export default function Insights() {
  const insights = useQuery({
    queryKey: qk.insights(),
    queryFn: () => api.insights(),
    staleTime: 5 * 60 * 1000, // server caches 5 min anyway
  })

  return (
    <>
      <PageHeader title="Claude Insights" sub="Aggregate-only analysis — no PII leaves the server" />
      <QueryBoundary query={insights} skeletonRows={4} empty={(d) => d.insights.length === 0}>
        {(d) => (
          <div className="max-w-3xl space-y-3">
            {d.insights.map((ins, i) => (
              <Card key={i} className="flex items-start gap-3">
                <span className="mt-0.5 rounded-sm bg-ai/15 p-1.5 text-ai">
                  <Sparkles className="h-4 w-4" />
                </span>
                <div className="min-w-0">
                  <p className="text-[14px] leading-relaxed">{ins.finding}</p>
                  <p className="mt-1 font-mono text-[11px] text-text-faint">source: {ins.source}</p>
                </div>
              </Card>
            ))}
            <p className="pt-1 text-[12px] text-text-faint">generated by: {d.generated_by}</p>
          </div>
        )}
      </QueryBoundary>
    </>
  )
}
